import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RootClient from "./rootClient";
import Header from "./components/Header";
import Footer from "./components/Footer";
import fazzle from "./fazzle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased px-4 md:px-4 lg:px-4 xl:px-36 2xl:px-48 3xl:px-64 bg-[var(--color-background)]`}
      >
        <RootClient>
          <Header title={fazzle.productName} />
          {children}
          <Footer />
        </RootClient>
      </body>
    </html>
  );
}
